// Add new product to the database
POST http://localhost:8080/api/v1/admin
Content-Type: application/json
Accept: application/json

{
  "brand": "Bombbar",
  "category": "cookie",
  "name": "Protein cookie",
  "flavour": "Chocolate brownie",
  "caloriesPer100Gram": 271,
  "weight": 40
}

###

// Get info about the product from the database
GET http://localhost:8080/api/v1/client?brand=Bombbar
Accept: application/json

###
